fix: fix error TS2339: Property 'sourceFileDir' does not exist on type '{}'
Refs: https://bobbyhadz.com/blog/typescript-property-does-not-exist-on-type